#!/usr/bin/env python3
"""Build the GitHub wiki of Bartleby from its Markdown documents.

Each document in DOCUMENTS becomes a branch of the tree menu in
_Sidebar.md, rooted at the text of its first H1. Its introduction, the
text between the H1 and the first section, becomes an overview page,
which the root of its branch links to. Each ## section becomes a page of
its own, named with the label of the document, as in "Bartleby Binder".
Its ### headings and deeper become entries under it in the menu.

The first H1 is left out, and so is the table of contents: a section
named Contents or Table of Contents, or a **Contents** line with its list
of links. The image right below the H1 is left out too, because every
page gets the logo instead.

Links are rewritten for the wiki: a link to a section or a document
leads to its page, a relative link to another file leads to the file in
the repository, and a relative image path, now or in the future, loads
the image from the repository. Text inside code is never changed.

Each page written here starts with GENERATED_MARK. A page with the mark
that is no longer produced is deleted. A page without it, such as
Home.md, is never touched.

Usage:
    python3 tools/wiki/build_wiki.py --wiki <wiki clone> [--repo owner/name]
        [--branch main] [--source <repository root>]
"""

import argparse
import html
import os
import posixpath
import re
import sys
import urllib.parse

# The documents, in the order of the menu, and the label that starts the
# name of each of their section pages.
DOCUMENTS = [
    ("README.md", "Bartleby"),
    ("Users_Guide.md", "User's Guide"),
    ("Localization_README.md", "Localization"),
]

LOGO = "images/bartleby-logo.png"
LOGO_WIDTH = 160

GENERATED_MARK = "<!-- Generated by tools/wiki/build_wiki.py from"
SIDEBAR = "_Sidebar.md"

# Characters left as they are in the address of a page. An apostrophe is
# encoded, so that the address is the same in Markdown and in HTML.
PAGE_SAFE = "-(),"

CONTENTS_TITLES = {"contents", "table of contents"}

FENCE = re.compile(r"^\s{0,3}(`{3,}|~{3,})")
HEADING = re.compile(r"^(#{1,6})\s+(.*?)\s*#*\s*$")
IMAGE_ONLY = re.compile(r"^\s*(!\[[^\]]*\]\([^)]*\)|<img\b[^>]*>)\s*$")
CONTENTS_LABEL = re.compile(r"^\s*(\*\*|__)(table of contents|contents)\1:?\s*$", re.IGNORECASE)
ANCHOR_ITEM = re.compile(r"^\s*([-*+]|\d+\.)\s+\[[^\]]*\]\(#[^)]*\)\s*$")
SCHEME = re.compile(r"^[a-zA-Z][a-zA-Z0-9+.-]*:")
HTML_ATTRIBUTE = re.compile(r"(<(?:img|a)\b[^>]*?\s(?:src|href)=)([\"'])([^\"']*)\2", re.IGNORECASE)
REFERENCE = re.compile(r"^(\s{0,3}\[[^\]]+\]:\s*)(\S+)(.*)$")


class Section:
    """A ## section: its page, its lines, and its ### and deeper headings."""

    def __init__(self, title, slug, page):
        self.title = title
        self.slug = slug
        self.page = page
        self.lines = []
        # (level, title, slug) for each heading below the section.
        self.headings = []


class Document:
    """A Markdown document split into an overview and sections."""

    def __init__(self, source, label):
        self.source = source
        self.label = label
        self.title = ""
        self.root_page = ""
        self.intro = []
        self.sections = []
        # Each anchor of the document: slug to (page, fragment or None).
        self.anchors = {}


def plain_text(text):
    """Return the heading text without Markdown markup or HTML."""
    text = re.sub(r"<[^>]+>", "", text)
    text = re.sub(r"!?\[([^\]]*)\]\([^)]*\)", r"\1", text)
    return text.replace("`", "").replace("**", "").replace("__", "").strip()


def slug(text):
    """Return the anchor GitHub makes for a heading."""
    lowered = plain_text(text).lower()
    kept = "".join(ch for ch in lowered if ch.isalnum() or ch in " -_")
    return kept.replace(" ", "-")


def unique_slug(text, seen):
    """Return slug(text), numbered as GitHub numbers repeated headings."""
    base = slug(text)
    count = seen.get(base, 0)
    seen[base] = count + 1
    return base if count == 0 else f"{base}-{count}"


def page_name(title):
    """Return the wiki file name, without .md, for a page title."""
    name = re.sub(r'[\\/:*?"<>|#%]', "", plain_text(title))
    return re.sub(r"\s+", "-", name.strip())


def lines_and_code(lines):
    """Yield each line with True when it is inside a fenced code block."""
    fence = None
    for line in lines:
        match = FENCE.match(line)
        if fence is None and match:
            fence = match.group(1)[0] * 3
            yield line, True
        elif fence is not None:
            if match and match.group(1).startswith(fence):
                fence = None
            yield line, True
        else:
            yield line, False


def drop_contents_lists(lines):
    """Remove a **Contents** line and the list of anchor links after it."""
    result = []
    skipping = False
    for line, code in lines_and_code(lines):
        if not code and CONTENTS_LABEL.match(line):
            skipping = True
            continue
        if skipping and (line.strip() == "" or ANCHOR_ITEM.match(line)):
            continue
        skipping = False
        result.append(line)
    return result


def parse(source, label, text):
    """Split the text of one document into its overview and sections."""
    document = Document(source, label)
    seen = {}
    section = None
    skipped_section = False
    after_title = False
    for line, code in lines_and_code(text.splitlines()):
        match = None if code else HEADING.match(line)
        if match and not document.title and len(match.group(1)) == 1:
            document.title = plain_text(match.group(2))
            document.root_page = page_name(document.title)
            after_title = True
            continue
        if after_title:
            # The image right below the H1 gives way to the logo.
            if line.strip() == "":
                continue
            after_title = False
            if IMAGE_ONLY.match(line):
                continue
        if match and len(match.group(1)) == 2:
            title = match.group(2)
            anchor = unique_slug(title, seen)
            if plain_text(title).lower() in CONTENTS_TITLES:
                section = None
                skipped_section = True
                continue
            skipped_section = False
            section = Section(plain_text(title), anchor,
                              page_name(f"{label} {plain_text(title)}"))
            document.sections.append(section)
            document.anchors[anchor] = (section.page, None)
            continue
        if match and len(match.group(1)) > 2:
            anchor = unique_slug(match.group(2), seen)
            if section is not None:
                section.headings.append((len(match.group(1)), plain_text(match.group(2)), anchor))
                document.anchors[anchor] = (section.page, anchor)
        if skipped_section:
            continue
        if section is None:
            document.intro.append(line)
        else:
            section.lines.append(line)
    if not document.title:
        raise ValueError(f"{source} has no H1")
    document.intro = drop_contents_lists(document.intro)
    return document


class Linker:
    """Rewrite the links of a document for the wiki."""

    def __init__(self, documents, repo, branch):
        self.by_source = {d.source: d for d in documents}
        self.repo = repo
        self.branch = branch

    def page_url(self, page, fragment=None):
        url = f"/{self.repo}/wiki/{urllib.parse.quote(page, safe=PAGE_SAFE)}"
        return url + (f"#{fragment}" if fragment else "")

    def target(self, document, target, image):
        """Return the wiki target for a link or image target."""
        if target.startswith("#"):
            page, fragment = document.anchors.get(target[1:], (document.root_page, target[1:]))
            return self.page_url(page, fragment)
        if SCHEME.match(target) or target.startswith("/"):
            return target
        path, _, fragment = target.partition("#")
        path = posixpath.normpath(urllib.parse.unquote(path))
        if path.startswith("../"):
            return target
        if not image and path in self.by_source:
            other = self.by_source[path]
            if fragment and fragment in other.anchors:
                page, anchor = other.anchors[fragment]
                return self.page_url(page, anchor)
            return self.page_url(other.root_page)
        quoted = urllib.parse.quote(path)
        if image:
            return f"https://raw.githubusercontent.com/{self.repo}/{self.branch}/{quoted}"
        return f"https://github.com/{self.repo}/blob/{self.branch}/{quoted}" + (
            f"#{fragment}" if fragment else "")

    def rewrite_markdown_links(self, document, text):
        """Rewrite every ](target) in text, nested images included."""
        out = []
        i = 0
        while True:
            j = text.find("](", i)
            if j < 0:
                out.append(text[i:])
                return "".join(out)
            end = self.closing_parenthesis(text, j + 2)
            if end < 0:
                out.append(text[i:])
                return "".join(out)
            inner = text[j + 2:end]
            target, title = (inner.split(None, 1) + [""])[:2] if inner.strip() else ("", "")
            image = self.is_image(text, j)
            new_target = self.target(document, target, image) if target else target
            out.append(text[i:j + 2])
            out.append(new_target + (" " + title if title else ""))
            out.append(")")
            i = end + 1

    @staticmethod
    def closing_parenthesis(text, start):
        depth = 0
        for k in range(start, len(text)):
            if text[k] == "(":
                depth += 1
            elif text[k] == ")":
                if depth == 0:
                    return k
                depth -= 1
        return -1

    @staticmethod
    def is_image(text, close):
        """Return True when the ] at close ends the text of an image."""
        depth = 0
        for k in range(close - 1, -1, -1):
            if text[k] == "]":
                depth += 1
            elif text[k] == "[":
                if depth == 0:
                    return k > 0 and text[k - 1] == "!"
                depth -= 1
        return False

    def rewrite_line(self, document, line):
        """Rewrite the links of one line outside code, and not in code spans."""
        match = REFERENCE.match(line)
        if match:
            return match.group(1) + self.target(document, match.group(2), False) + match.group(3)
        parts = re.split(r"(`+[^`]*`+)", line)
        for k in range(0, len(parts), 2):
            part = self.rewrite_markdown_links(document, parts[k])
            parts[k] = HTML_ATTRIBUTE.sub(
                lambda m: m.group(1) + m.group(2)
                + self.target(document, m.group(3), m.group(1).lower().startswith("<img"))
                + m.group(2), part)
        return "".join(parts)

    def rewrite(self, document, lines):
        return [line if code else self.rewrite_line(document, line)
                for line, code in lines_and_code(lines)]


def logo_html(repo, branch):
    src = f"https://raw.githubusercontent.com/{repo}/{branch}/{LOGO}"
    return f'<img src="{src}" alt="Bartleby logo" width="{LOGO_WIDTH}">'


def trim(lines):
    """Remove blank lines at both ends."""
    while lines and not lines[0].strip():
        lines = lines[1:]
    while lines and not lines[-1].strip():
        lines = lines[:-1]
    return lines


def page_text(document, body, linker, navigation):
    head = [f"{GENERATED_MARK} {document.source}. Edit that file instead. -->",
            logo_html(linker.repo, linker.branch), ""]
    tail = ["", "---", "", navigation] if navigation else []
    return "\n".join(head + trim(linker.rewrite(document, body)) + tail) + "\n"


def navigation(document, index, linker):
    """Return the line that leads to the previous page, the overview, and
    the next page. The overview is index -1, and comes before the first
    section. A page never links to itself, and the first section, whose
    previous page is the overview, does not repeat it."""
    pages = [(document.title, document.root_page)] + [(s.title, s.page) for s in document.sections]
    position = index + 1
    links = []
    if position > 0:
        title, page = pages[position - 1]
        links.append(f"[← {title}]({linker.page_url(page)})")
    if position > 1:
        links.append(f"[{document.title}]({linker.page_url(document.root_page)})")
    if position + 1 < len(pages):
        title, page = pages[position + 1]
        links.append(f"[{title} →]({linker.page_url(page)})")
    return " · ".join(links)


def sidebar(documents, linker):
    """Return _Sidebar.md: one collapsible branch per document, open at
    first, as are the branches of the sections inside it."""
    def link(url, text):
        return f'<a href="{html.escape(url)}">{html.escape(text)}</a>'

    out = [f"{GENERATED_MARK} {', '.join(d.source for d in documents)}. Edit those files instead. -->",
           "", f'<p>{link(f"/{linker.repo}/wiki", "Home")}</p>', ""]
    for document in documents:
        out.append("<details open>")
        out.append(f"<summary>{link(linker.page_url(document.root_page), document.title)}</summary>")
        out.append("<ul>")
        for section in document.sections:
            url = linker.page_url(section.page)
            if not section.headings:
                out.append(f"<li>{link(url, section.title)}</li>")
                continue
            out.append(f"<li><details open><summary>{link(url, section.title)}</summary>")
            out.append("<ul>")
            for _, title, anchor in section.headings:
                out.append(f"<li>{link(linker.page_url(section.page, anchor), title)}</li>")
            out.append("</ul>")
            out.append("</details></li>")
        out.append("</ul>")
        out.append("</details>")
        out.append("")
    return "\n".join(out)


def build(source_dir, repo, branch):
    """Return the wiki files to write: file name to text."""
    documents = []
    for source, label in DOCUMENTS:
        with open(os.path.join(source_dir, source), encoding="utf-8") as handle:
            documents.append(parse(source, label, handle.read()))
    linker = Linker(documents, repo, branch)
    files = {}
    for document in documents:
        files[f"{document.root_page}.md"] = page_text(
            document, document.intro, linker, navigation(document, -1, linker))
        for index, section in enumerate(document.sections):
            files[f"{section.page}.md"] = page_text(
                document, section.lines, linker, navigation(document, index, linker))
    names = [d.root_page for d in documents] + [s.page for d in documents for s in d.sections]
    repeated = sorted({n for n in names if names.count(n) > 1})
    if repeated:
        raise ValueError(f"two pages would have the same name: {', '.join(repeated)}")
    files[SIDEBAR] = sidebar(documents, linker)
    return files


def write(wiki_dir, files):
    """Write the files, and delete generated pages that are no longer made.
    Returns the names written and the names deleted."""
    written = []
    deleted = []
    for name in sorted(os.listdir(wiki_dir)):
        path = os.path.join(wiki_dir, name)
        if not name.endswith(".md") or name in files or not os.path.isfile(path):
            continue
        with open(path, encoding="utf-8") as handle:
            if handle.readline().startswith(GENERATED_MARK):
                os.remove(path)
                deleted.append(name)
    for name, text in sorted(files.items()):
        path = os.path.join(wiki_dir, name)
        if os.path.exists(path):
            with open(path, encoding="utf-8") as handle:
                if handle.read() == text:
                    continue
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(text)
        written.append(name)
    return written, deleted


def main():
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--wiki", required=True, help="the clone of the wiki repository")
    parser.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY", "Galvarcus/bartleby"),
                        help="owner/name of the repository")
    parser.add_argument("--branch", default="main", help="the branch that images and files load from")
    parser.add_argument("--source", default=root, help="the repository root with the documents")
    args = parser.parse_args()
    try:
        files = build(args.source, args.repo, args.branch)
    except (OSError, ValueError) as error:
        print(f"build_wiki: {error}", file=sys.stderr)
        return 1
    written, deleted = write(args.wiki, files)
    print(f"{len(files)} pages, {len(written)} written, {len(deleted)} deleted")
    for name in deleted:
        print(f"  deleted {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
